### ISSUE TITLE
Received malformed response from transform <account-id>:count

### ISSUE THREAD

**Issue by rahul-amzn** [aws-cloudformation/aws-cloudformation-macros#29]
If there is `%` anywhere in CloudFormation template, it gives below error. 

`Received malformed response from transform 12345XXXXX::Count`

For example: 
```
  DiskSpaceAlarm:
    Type: AWS::CloudWatch::Alarm
    Count: !Ref Instancescount
    Properties:
      AlarmDescription: Over 95 of volume space is in use
      AlarmActions:
      - !Ref SNSTopicEc2
      MetricName: "% Free Space"
```

There should be either some 'delimiter' or lambda should consider only specific (e.g. `%d`) as a placeholder not all `%`.
